version: '3.7'

services:
  
  react-container:
    container_name: react-container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:4000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
